export type PropertyType =
  | "apartment"
  | "house"
  | "villa"
  | "studio"
  | "loft"
  | "cottage";

export type Listing = {
  id: string;
  title: string;
  description: string;
  address: string;
  city: string;
  country: string;
  coordinates: {
    lat: number;
    lng: number;
  };
  pricePerNight: number;
  propertyType: PropertyType;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  guests: number;
  rating: number;
  reviewCount: number;
  images: string[];
  amenities: string[];
  host: {
    name: string;
    avatar: string;
    isSuperhost: boolean;
  };
  isFavorite: boolean;
  isNew: boolean;
  instantBook: boolean;
};

const cameraImages = [
  "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?w=900&h=700&fit=crop",
];

const audioImages = [
  "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=900&h=700&fit=crop",
];

const cyclingImages = [
  "https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1529422643029-d4585747aaf2?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=900&h=700&fit=crop",
];

const campingImages = [
  "https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1470246973918-29a93221c455?w=900&h=700&fit=crop",
];

const droneImages = [
  "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1521405924368-64c5b84bec60?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1524143986875-3b098d78b363?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=900&h=700&fit=crop",
];

const gamingImages = [
  "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=900&h=700&fit=crop",
  "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=900&h=700&fit=crop",
];

export const listings: Listing[] = [
  {
    id: "gear-1",
    title: "Sony FX3 Creator Cinema Kit",
    description: "Full-frame camera kit with cage, monitor, and dual batteries for short-form shoots.",
    address: "1141 W Colfax Ave",
    city: "Denver",
    country: "USA",
    coordinates: { lat: 39.7392, lng: -104.9903 },
    pricePerNight: 185,
    propertyType: "apartment",
    bedrooms: 3,
    beds: 5,
    bathrooms: 2,
    guests: 6,
    rating: 4.9,
    reviewCount: 132,
    images: cameraImages,
    amenities: ["Damage waiver", "Same-day pickup", "Tripod included", "ND filters"],
    host: {
      name: "Mia Park",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=MiaPark",
      isSuperhost: true,
    },
    isFavorite: true,
    isNew: false,
    instantBook: true,
  },
  {
    id: "gear-2",
    title: "Canon R6 Mark II Event Bundle",
    description: "Low-light camera setup with two lenses and flash for events and portraits.",
    address: "219 SW Pine St",
    city: "Portland",
    country: "USA",
    coordinates: { lat: 45.5152, lng: -122.6784 },
    pricePerNight: 165,
    propertyType: "apartment",
    bedrooms: 2,
    beds: 4,
    bathrooms: 2,
    guests: 4,
    rating: 4.8,
    reviewCount: 88,
    images: cameraImages,
    amenities: ["Insurance included", "Lens cleaning kit", "Express return"],
    host: {
      name: "Noah Kim",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=NoahKim",
      isSuperhost: true,
    },
    isFavorite: false,
    isNew: true,
    instantBook: true,
  },
  {
    id: "gear-3",
    title: "Rode Podcast Studio Rack",
    description: "Two-mic recording station with interface, acoustic panels, and backup recorder.",
    address: "802 E 6th St",
    city: "Austin",
    country: "USA",
    coordinates: { lat: 30.2672, lng: -97.7431 },
    pricePerNight: 95,
    propertyType: "house",
    bedrooms: 2,
    beds: 4,
    bathrooms: 3,
    guests: 5,
    rating: 4.7,
    reviewCount: 61,
    images: audioImages,
    amenities: ["On-site sound check", "USB-C cables", "Pop filters"],
    host: {
      name: "Camden Lee",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=CamdenLee",
      isSuperhost: false,
    },
    isFavorite: true,
    isNew: false,
    instantBook: true,
  },
  {
    id: "gear-4",
    title: "Pioneer DJ Booth Starter Set",
    description: "Controller, monitors, and lighting for club practice sessions and pop-up sets.",
    address: "1430 2nd Ave",
    city: "Seattle",
    country: "USA",
    coordinates: { lat: 47.6062, lng: -122.3321 },
    pricePerNight: 140,
    propertyType: "house",
    bedrooms: 3,
    beds: 5,
    bathrooms: 4,
    guests: 8,
    rating: 4.9,
    reviewCount: 109,
    images: audioImages,
    amenities: ["Speaker stands", "MIDI cables", "Late-night pickup"],
    host: {
      name: "Zara Patel",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ZaraPatel",
      isSuperhost: true,
    },
    isFavorite: false,
    isNew: true,
    instantBook: false,
  },
  {
    id: "gear-5",
    title: "Trek Domane Carbon Road Package",
    description: "Race-ready road bike with helmet, meter pedals, and roadside repair kit.",
    address: "1745 28th St",
    city: "Boulder",
    country: "USA",
    coordinates: { lat: 40.015, lng: -105.2705 },
    pricePerNight: 125,
    propertyType: "villa",
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    guests: 2,
    rating: 4.8,
    reviewCount: 73,
    images: cyclingImages,
    amenities: ["Bike fit included", "Tube pack", "GPS mount"],
    host: {
      name: "Ethan Ruiz",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=EthanRuiz",
      isSuperhost: true,
    },
    isFavorite: true,
    isNew: false,
    instantBook: true,
  },
  {
    id: "gear-6",
    title: "Specialized Trail e-MTB Set",
    description: "Electric mountain bike package with charger, pads, and hydration vest.",
    address: "5025 N Harbor Dr",
    city: "San Diego",
    country: "USA",
    coordinates: { lat: 32.7157, lng: -117.1611 },
    pricePerNight: 160,
    propertyType: "villa",
    bedrooms: 2,
    beds: 3,
    bathrooms: 3,
    guests: 2,
    rating: 4.9,
    reviewCount: 96,
    images: cyclingImages,
    amenities: ["Helmet included", "Trail map pack", "Battery swap option"],
    host: {
      name: "Ava Brooks",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=AvaBrooks",
      isSuperhost: true,
    },
    isFavorite: false,
    isNew: true,
    instantBook: true,
  },
  {
    id: "gear-7",
    title: "4-Person Basecamp Weekend Kit",
    description: "Tent, stove, lanterns, and insulated sleeping system for quick camp escapes.",
    address: "8812 N 3rd St",
    city: "Phoenix",
    country: "USA",
    coordinates: { lat: 33.4484, lng: -112.074 },
    pricePerNight: 84,
    propertyType: "studio",
    bedrooms: 4,
    beds: 8,
    bathrooms: 4,
    guests: 6,
    rating: 4.6,
    reviewCount: 57,
    images: campingImages,
    amenities: ["Cooler included", "Fuel canister", "Camp chairs"],
    host: {
      name: "Leo Clark",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=LeoClark",
      isSuperhost: false,
    },
    isFavorite: false,
    isNew: false,
    instantBook: true,
  },
  {
    id: "gear-8",
    title: "Winter Touring Shelter Bundle",
    description: "Cold-weather tent system, avalanche beacons, and insulated cook station.",
    address: "311 W 200 S",
    city: "Salt Lake City",
    country: "USA",
    coordinates: { lat: 40.7608, lng: -111.891 },
    pricePerNight: 112,
    propertyType: "studio",
    bedrooms: 3,
    beds: 7,
    bathrooms: 5,
    guests: 5,
    rating: 4.7,
    reviewCount: 48,
    images: campingImages,
    amenities: ["Emergency beacon", "Snow stakes", "Warm liner set"],
    host: {
      name: "Iris Shaw",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=IrisShaw",
      isSuperhost: true,
    },
    isFavorite: true,
    isNew: false,
    instantBook: false,
  },
  {
    id: "gear-9",
    title: "DJI Mavic 3 Fly More Pack",
    description: "Long-range drone bundle with ND set, charging dock, and dual operator screens.",
    address: "810 Broadway",
    city: "Nashville",
    country: "USA",
    coordinates: { lat: 36.1627, lng: -86.7816 },
    pricePerNight: 210,
    propertyType: "loft",
    bedrooms: 2,
    beds: 4,
    bathrooms: 3,
    guests: 3,
    rating: 4.9,
    reviewCount: 143,
    images: droneImages,
    amenities: ["Flight insurance", "Landing pad", "48-hour support"],
    host: {
      name: "Remy Foster",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=RemyFoster",
      isSuperhost: true,
    },
    isFavorite: true,
    isNew: true,
    instantBook: true,
  },
  {
    id: "gear-10",
    title: "FPV Racing Drone Starter Crate",
    description: "Complete FPV setup with goggles, spare props, and training simulator access.",
    address: "155 NE 40th St",
    city: "Miami",
    country: "USA",
    coordinates: { lat: 25.7617, lng: -80.1918 },
    pricePerNight: 132,
    propertyType: "loft",
    bedrooms: 3,
    beds: 5,
    bathrooms: 4,
    guests: 4,
    rating: 4.7,
    reviewCount: 77,
    images: droneImages,
    amenities: ["Extra propellers", "Practice gates", "Battery bag"],
    host: {
      name: "Skye Morgan",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=SkyeMorgan",
      isSuperhost: false,
    },
    isFavorite: false,
    isNew: false,
    instantBook: true,
  },
  {
    id: "gear-11",
    title: "Pro Streaming Battle Station",
    description: "Dual-PC gaming setup with capture card, scene lights, and creator mic arm.",
    address: "227 W Hubbard St",
    city: "Chicago",
    country: "USA",
    coordinates: { lat: 41.8781, lng: -87.6298 },
    pricePerNight: 118,
    propertyType: "cottage",
    bedrooms: 2,
    beds: 4,
    bathrooms: 4,
    guests: 3,
    rating: 4.8,
    reviewCount: 84,
    images: gamingImages,
    amenities: ["Scene presets", "Cable management", "Overlays included"],
    host: {
      name: "Jules Quinn",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=JulesQuinn",
      isSuperhost: true,
    },
    isFavorite: false,
    isNew: true,
    instantBook: true,
  },
  {
    id: "gear-12",
    title: "VR Event Pop-up Arena Kit",
    description: "Portable VR package for activations with signage, chargers, and queue display.",
    address: "443 W 14th St",
    city: "New York",
    country: "USA",
    coordinates: { lat: 40.7128, lng: -74.006 },
    pricePerNight: 225,
    propertyType: "cottage",
    bedrooms: 4,
    beds: 8,
    bathrooms: 5,
    guests: 10,
    rating: 4.9,
    reviewCount: 101,
    images: gamingImages,
    amenities: ["On-site setup", "Safety mats", "Fast replacement"],
    host: {
      name: "Theo Reed",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=TheoReed",
      isSuperhost: true,
    },
    isFavorite: true,
    isNew: false,
    instantBook: false,
  },
  {
    id: "gear-13",
    title: "Portable Film Lighting Grid",
    description: "RGB panel package with softboxes and remote dimmer for interviews and product shots.",
    address: "780 N Highland Ave",
    city: "Los Angeles",
    country: "USA",
    coordinates: { lat: 34.0522, lng: -118.2437 },
    pricePerNight: 138,
    propertyType: "house",
    bedrooms: 3,
    beds: 5,
    bathrooms: 4,
    guests: 5,
    rating: 4.8,
    reviewCount: 92,
    images: cameraImages,
    amenities: ["Diffusion kit", "Sandbags", "Color cards"],
    host: {
      name: "Rae Dalton",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=RaeDalton",
      isSuperhost: false,
    },
    isFavorite: false,
    isNew: false,
    instantBook: true,
  },
  {
    id: "gear-14",
    title: "Wedding Photo Duo Package",
    description: "Two-camera setup with portrait primes, wireless flash triggers, and backup drive.",
    address: "940 Peachtree St NE",
    city: "Atlanta",
    country: "USA",
    coordinates: { lat: 33.749, lng: -84.388 },
    pricePerNight: 196,
    propertyType: "apartment",
    bedrooms: 3,
    beds: 6,
    bathrooms: 3,
    guests: 6,
    rating: 4.9,
    reviewCount: 128,
    images: cameraImages,
    amenities: ["Lens insurance", "Rain cover", "Color checker"],
    host: {
      name: "Kira Holt",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=KiraHolt",
      isSuperhost: true,
    },
    isFavorite: true,
    isNew: false,
    instantBook: true,
  },
  {
    id: "gear-15",
    title: "Field Audio Interview Pack",
    description: "Compact audio kit with lavs, boom mic, and timecode recorder for documentary crews.",
    address: "1810 Rue Sainte-Catherine O",
    city: "Montreal",
    country: "Canada",
    coordinates: { lat: 45.5017, lng: -73.5673 },
    pricePerNight: 104,
    propertyType: "house",
    bedrooms: 2,
    beds: 4,
    bathrooms: 3,
    guests: 4,
    rating: 4.7,
    reviewCount: 59,
    images: audioImages,
    amenities: ["Rechargeable battery bank", "Wind protection", "Hard case"],
    host: {
      name: "Nina Vale",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=NinaVale",
      isSuperhost: false,
    },
    isFavorite: false,
    isNew: true,
    instantBook: true,
  },
  {
    id: "gear-16",
    title: "Urban Courier Bike Fleet Kit",
    description: "Three-bike city set with helmets, pannier bags, and tracking mounts.",
    address: "390 W Cordova St",
    city: "Vancouver",
    country: "Canada",
    coordinates: { lat: 49.2827, lng: -123.1207 },
    pricePerNight: 148,
    propertyType: "villa",
    bedrooms: 3,
    beds: 6,
    bathrooms: 4,
    guests: 6,
    rating: 4.8,
    reviewCount: 68,
    images: cyclingImages,
    amenities: ["Helmet cleaning", "Bike locks", "Frame lights"],
    host: {
      name: "Owen Cross",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=OwenCross",
      isSuperhost: true,
    },
    isFavorite: false,
    isNew: false,
    instantBook: false,
  },
  {
    id: "gear-17",
    title: "Creator Office Workstation Set",
    description: "Desk setup with monitor arm, key light, and webcam for remote brand shoots.",
    address: "96 Shoreditch High St",
    city: "London",
    country: "UK",
    coordinates: { lat: 51.5074, lng: -0.1278 },
    pricePerNight: 89,
    propertyType: "cottage",
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    guests: 2,
    rating: 4.6,
    reviewCount: 53,
    images: gamingImages,
    amenities: ["Cable kit", "Desk mount", "Audio interface"],
    host: {
      name: "Sage Bennett",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=SageBennett",
      isSuperhost: false,
    },
    isFavorite: true,
    isNew: false,
    instantBook: true,
  },
  {
    id: "gear-18",
    title: "Street Documentary Drone Rig",
    description: "Compact travel drone setup with fast charger and compliance checklist.",
    address: "27 Linienstrasse",
    city: "Berlin",
    country: "Germany",
    coordinates: { lat: 52.52, lng: 13.405 },
    pricePerNight: 172,
    propertyType: "loft",
    bedrooms: 2,
    beds: 4,
    bathrooms: 3,
    guests: 3,
    rating: 4.9,
    reviewCount: 117,
    images: droneImages,
    amenities: ["Flight log template", "Insurance PDF", "Travel case"],
    host: {
      name: "Arlo Finch",
      avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ArloFinch",
      isSuperhost: true,
    },
    isFavorite: true,
    isNew: true,
    instantBook: true,
  },
];

export const propertyTypeLabels: Record<PropertyType, string> = {
  apartment: "Cameras",
  house: "Audio",
  villa: "Cycling",
  studio: "Camping",
  loft: "Drones",
  cottage: "Gaming",
};
