export type LocationCategory = {
  id: string
  name: string
  icon: string
  color: string
}

export type Location = {
  id: string
  name: string
  description: string
  address: string
  categoryId: string
  coordinates: {
    lat: number
    lng: number
  }
  rating: number
  tags: string[]
  createdAt: string
  isFavorite: boolean
  visitCount: number
  lastVisited?: string
}

export const categories: LocationCategory[] = [
  { id: "food-drops", name: "Food Drops", icon: "utensils", color: "#ef4444" },
  {
    id: "creator-cafes",
    name: "Creator Cafes",
    icon: "coffee",
    color: "#f97316",
  },
  {
    id: "night-sessions",
    name: "Night Sessions",
    icon: "wine",
    color: "#8b5cf6",
  },
  {
    id: "park-meetups",
    name: "Park Meetups",
    icon: "trees",
    color: "#22c55e",
  },
  {
    id: "photo-spots",
    name: "Photo Spots",
    icon: "landmark",
    color: "#3b82f6",
  },
  {
    id: "pop-up-markets",
    name: "Pop-up Markets",
    icon: "shopping-bag",
    color: "#ec4899",
  },
  {
    id: "weekend-stays",
    name: "Weekend Stays",
    icon: "bed",
    color: "#06b6d4",
  },
  {
    id: "fit-check-zones",
    name: "Fit Check Zones",
    icon: "dumbbell",
    color: "#eab308",
  },
]

export const tags = [
  { id: "trending", name: "Trending" },
  { id: "reels-hotspot", name: "Reels Hotspot" },
  { id: "rooftop", name: "Rooftop" },
  { id: "late-night", name: "Late Night" },
  { id: "pet-friendly", name: "Pet Friendly" },
  { id: "collab-friendly", name: "Collab Friendly" },
  { id: "fast-wifi", name: "Fast WiFi" },
  { id: "sunset", name: "Sunset Views" },
  { id: "live-music", name: "Live Music" },
  { id: "budget", name: "Budget Friendly" },
  { id: "quiet-editing", name: "Quiet Editing" },
  { id: "event-ready", name: "Event Ready" },
  { id: "fit-check", name: "Fit Check" },
]

const createLocation = (
  id: string,
  name: string,
  description: string,
  address: string,
  categoryId: string,
  lat: number,
  lng: number,
  rating: number,
  tagIds: string[],
  createdAt: string,
  visitCount: number,
  isFavorite: boolean = false,
  lastVisited?: string
): Location => ({
  id,
  name,
  description,
  address,
  categoryId,
  coordinates: { lat, lng },
  rating,
  tags: tagIds,
  createdAt,
  isFavorite,
  visitCount,
  lastVisited,
})

export const locations: Location[] = [
  createLocation(
    "spot-1",
    "Late Plate Run Club",
    "Night food truck cluster where creators post quick review reels after run meetups.",
    "1422 S Congress Ave, Austin, TX",
    "food-drops",
    30.2496,
    -97.7494,
    4.8,
    ["trending", "reels-hotspot", "late-night", "budget"],
    "2025-11-21",
    312,
    true,
    "2026-02-14"
  ),
  createLocation(
    "spot-2",
    "Harbor Slice Drop",
    "Pop-up pizza dock with creator menu collabs every Friday night.",
    "912 Alaskan Way, Seattle, WA",
    "food-drops",
    47.6075,
    -122.3406,
    4.7,
    ["event-ready", "live-music", "trending"],
    "2025-10-03",
    245,
    false,
    "2026-02-11"
  ),
  createLocation(
    "spot-3",
    "Neon Noodle Garage",
    "Street noodle kitchen used for food edits, creator duets, and challenge videos.",
    "630 N Broadway, Los Angeles, CA",
    "food-drops",
    34.0519,
    -118.2428,
    4.6,
    ["late-night", "reels-hotspot", "trending"],
    "2025-08-16",
    286,
    true,
    "2026-02-08"
  ),
  createLocation(
    "spot-4",
    "Cutscene Coffee Lab",
    "Creator-friendly cafe with wall outlets, podcast corners, and fast upload speeds.",
    "410 W Lake St, Chicago, IL",
    "creator-cafes",
    41.8856,
    -87.6386,
    4.9,
    ["fast-wifi", "collab-friendly", "quiet-editing"],
    "2025-09-27",
    199,
    true,
    "2026-02-16"
  ),
  createLocation(
    "spot-5",
    "Edit Hour Cafe",
    "Early-morning creator grind spot known for silent edit blocks and standing desks.",
    "118 NW 13th Ave, Portland, OR",
    "creator-cafes",
    45.5244,
    -122.6846,
    4.8,
    ["quiet-editing", "fast-wifi", "budget"],
    "2025-07-02",
    177,
    false,
    "2026-02-12"
  ),
  createLocation(
    "spot-6",
    "Threadline Espresso",
    "Street-level cafe where local stylists and photographers run collab mornings.",
    "35 Prince St, New York, NY",
    "creator-cafes",
    40.7236,
    -73.9982,
    4.7,
    ["collab-friendly", "trending", "reels-hotspot"],
    "2025-12-01",
    289,
    true,
    "2026-02-18"
  ),
  createLocation(
    "spot-7",
    "Afterlight Rooftop",
    "Night skyline bar used for launch parties and social clips with city backdrops.",
    "201 Biscayne Blvd, Miami, FL",
    "night-sessions",
    25.7743,
    -80.1893,
    4.8,
    ["rooftop", "late-night", "event-ready", "live-music"],
    "2025-10-29",
    341,
    true,
    "2026-02-17"
  ),
  createLocation(
    "spot-8",
    "Blue Hour Social Hall",
    "Open-format music room where DJs test sets and creators stream live reactions.",
    "804 14th St NW, Washington, DC",
    "night-sessions",
    38.9016,
    -77.0325,
    4.6,
    ["live-music", "late-night", "collab-friendly"],
    "2025-06-14",
    213,
    false,
    "2026-01-29"
  ),
  createLocation(
    "spot-9",
    "Signal Loft Sessions",
    "Small venue for creator meetups, listening parties, and rooftop DJ recaps.",
    "1200 Broadway, Nashville, TN",
    "night-sessions",
    36.1604,
    -86.7782,
    4.7,
    ["rooftop", "event-ready", "trending"],
    "2025-09-10",
    228,
    false,
    "2026-02-07"
  ),
  createLocation(
    "spot-10",
    "Sunset Frames Park",
    "Open lawn where creators coordinate golden-hour portrait swaps and drone practice.",
    "500 N Harbor Dr, San Diego, CA",
    "park-meetups",
    32.7152,
    -117.173,
    4.9,
    ["sunset", "reels-hotspot", "pet-friendly"],
    "2025-05-04",
    268,
    true,
    "2026-02-15"
  ),
  createLocation(
    "spot-11",
    "Creator Picnic Commons",
    "Weekly meetup zone for collab circles, walking vlogs, and community intros.",
    "600 Atlantic Ave, Brooklyn, NY",
    "park-meetups",
    40.6827,
    -73.9755,
    4.7,
    ["collab-friendly", "pet-friendly", "trending"],
    "2025-08-09",
    204,
    false,
    "2026-02-09"
  ),
  createLocation(
    "spot-12",
    "Trail Loop Meetup Deck",
    "Fitness and lifestyle creators start routes here before posting split-screen recaps.",
    "1700 29th St, Boulder, CO",
    "park-meetups",
    40.0168,
    -105.2816,
    4.6,
    ["fit-check", "sunset", "budget"],
    "2025-07-23",
    149,
    false,
    "2026-01-31"
  ),
  createLocation(
    "spot-13",
    "Mirrorline Alley",
    "Street art corridor with reflective walls, top-ranked for outfit transitions.",
    "71 Peachtree St, Atlanta, GA",
    "photo-spots",
    33.7589,
    -84.3879,
    4.8,
    ["reels-hotspot", "trending", "budget"],
    "2025-11-03",
    271,
    true,
    "2026-02-13"
  ),
  createLocation(
    "spot-14",
    "Old Station Arches",
    "Historic brick arches and soft ambient light for editorial style posts.",
    "240 King St, Toronto, ON",
    "photo-spots",
    43.6487,
    -79.3748,
    4.7,
    ["quiet-editing", "sunset", "collab-friendly"],
    "2025-06-30",
    164,
    false,
    "2026-02-05"
  ),
  createLocation(
    "spot-15",
    "Skyline Frame Deck",
    "Raised city platform with day-to-night angles popular for launch countdown posts.",
    "2 Marina Blvd, San Francisco, CA",
    "photo-spots",
    37.8067,
    -122.4324,
    4.9,
    ["sunset", "rooftop", "reels-hotspot"],
    "2025-12-18",
    334,
    true,
    "2026-02-18"
  ),
  createLocation(
    "spot-16",
    "Studio Lane Market",
    "Weekend creator market with rotating thrift drops and handmade set props.",
    "8801 Melrose Ave, West Hollywood, CA",
    "pop-up-markets",
    34.0837,
    -118.3778,
    4.6,
    ["trending", "event-ready", "budget"],
    "2025-09-14",
    183,
    false,
    "2026-02-03"
  ),
  createLocation(
    "spot-17",
    "Canvas Flea Yard",
    "Outdoor pop-up where designers and short-form creators trade visual merch.",
    "301 S Ervay St, Dallas, TX",
    "pop-up-markets",
    32.7803,
    -96.7969,
    4.5,
    ["collab-friendly", "budget", "pet-friendly"],
    "2025-08-20",
    141,
    false,
    "2026-01-22"
  ),
  createLocation(
    "spot-18",
    "Pulse Pop Bazaar",
    "Night market with live hosts, mini stages, and creator challenge booths.",
    "12 W 21st St, New York, NY",
    "pop-up-markets",
    40.7415,
    -73.9918,
    4.7,
    ["late-night", "event-ready", "live-music"],
    "2025-10-08",
    259,
    true,
    "2026-02-10"
  ),
  createLocation(
    "spot-19",
    "Weekend Loft Suites",
    "Short-stay creator suites with wardrobe rails and edit nooks for campaign weekends.",
    "1450 W 18th St, Chicago, IL",
    "weekend-stays",
    41.8582,
    -87.6665,
    4.8,
    ["fast-wifi", "quiet-editing", "event-ready"],
    "2025-11-12",
    122,
    true,
    "2026-02-04"
  ),
  createLocation(
    "spot-20",
    "Harbor Studio Hotel",
    "Creator-focused boutique stay with in-room lighting kits and sound blankets.",
    "95 Main St, Vancouver, BC",
    "weekend-stays",
    49.2822,
    -123.1062,
    4.7,
    ["fast-wifi", "quiet-editing", "collab-friendly"],
    "2025-07-17",
    111,
    false,
    "2026-01-30"
  ),
  createLocation(
    "spot-21",
    "Downtown Recovery Suites",
    "Stay-and-shoot concept hotel for post-event editing and sponsored recap shoots.",
    "601 California St, Denver, CO",
    "weekend-stays",
    39.7415,
    -104.9899,
    4.6,
    ["event-ready", "quiet-editing", "budget"],
    "2025-05-29",
    97,
    false,
    "2026-01-21"
  ),
  createLocation(
    "spot-22",
    "Fit Reel Yard",
    "Open-air gym plaza used for form checks, brand demos, and weekly fitness collabs.",
    "1220 NW 2nd Ave, Miami, FL",
    "fit-check-zones",
    25.7861,
    -80.1989,
    4.8,
    ["fit-check", "trending", "event-ready"],
    "2025-12-05",
    274,
    true,
    "2026-02-16"
  ),
  createLocation(
    "spot-23",
    "Motion Lab Court",
    "Indoor training hub with mirrored walls for movement creators and dance edits.",
    "1090 W 6th St, Los Angeles, CA",
    "fit-check-zones",
    34.0488,
    -118.2576,
    4.7,
    ["reels-hotspot", "collab-friendly", "late-night"],
    "2025-06-05",
    236,
    false,
    "2026-02-06"
  ),
  createLocation(
    "spot-24",
    "Riverside Pace Club",
    "Run creator hotspot with sunrise and sunset loops mapped for social challenges.",
    "250 S Wacker Dr, Chicago, IL",
    "fit-check-zones",
    41.8788,
    -87.6377,
    4.6,
    ["fit-check", "sunset", "budget"],
    "2025-09-01",
    188,
    false,
    "2026-02-01"
  ),
]
